TERMUX_PKG_HOMEPAGE=https://saitoha.github.io/libsixel/
TERMUX_PKG_DESCRIPTION="Encoder/decoder implementation for DEC SIXEL graphics"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=1.8.5
TERMUX_PKG_SRCURL=https://github.com/saitoha/libsixel/archive/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=682ef295eb93f262db7d77b3a5e8ffcb6e3f5a9fc864d1a21cc5cd3c347a4b0e
TERMUX_PKG_DEPENDS="libcurl, libjpeg-turbo, libpng"
TERMUX_PKG_BREAKS="libsixel-dev"
TERMUX_PKG_REPLACES="libsixel-dev"
