TERMUX_PKG_HOMEPAGE=https://dev.lovelyhq.com/libburnia
TERMUX_PKG_DESCRIPTION="Library for reading, mastering and writing optical discs"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=1.5.0
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=http://files.libburnia-project.org/releases/libburn-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=582b12c236c1365211946f2fe3c254976af37bbec244051f7742a98ded9be2bd
TERMUX_PKG_BREAKS="libburn-dev"
TERMUX_PKG_REPLACES="libburn-dev"
